# environment.yml
name: rnaseq_env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - multiqc=1.24.1
  - fastqc
  - fastp
  - bowtie2
  - hisat2
  - samtools
  - subread
  - r-base
  - bioconductor-deseq2
  - r-tidyverse
  - sortmerna=4.3.6
  - ribodetector
